name: Build (Dev)
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Build plugin
        run: dotnet publish -c Release -f net8.0 WebhookDump/WebhookDump.csproj
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WebhookDump
          path: WebhookDump/bin/Release/net8.0/publish
